// scripts/tests/genres.js
// NOTE: Dàn phẳng, không còn nhóm. category = "general" cho tất cả.
// Giữ structure y hệt file cũ (description có thể rỗng để bạn điền sau).
db.genres.insertMany([
  // ---- PIN lên đầu ----
  {
    name: "Oneshot",
    slug: "oneshot",
    category: "general",
    description:
      "Truyện ngắn chỉ trong một chương, tập trung vào một tình huống tình dục cụ thể, không có cốt truyện dài dòng.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ---- A → Z (không nhóm) ----
  {
    name: "3D Hentai",
    slug: "3d-hentai",
    category: "general",
    description: "Truyện tranh hoặc video hentai sử dụng đồ họa 3D.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Action", slug: "action", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Adult", slug: "adult", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Adventure",
    slug: "adventure",
    category: "general",
    description:
      "Nhân vật bước vào hành trình phiêu lưu: thế giới fantasy, dị giới, hoặc vùng đất xa lạ. Nội dung kết hợp tình dục với yếu tố hành động, khám phá, và cốt truyện dài.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ahegao",
    slug: "ahegao",
    category: "general",
    description:
      "Biểu cảm nhân vật khi đạt cực khoái mãnh liệt: mắt đảo, lưỡi thè, mặt đỏ, nước dãi chảy ra. Thể hiện sự mất kiểm soát và khoái cảm tột độ.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Anal",
    slug: "anal",
    category: "general",
    description: "Quan hệ tình dục qua đường hậu môn.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Angel", slug: "angel", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Ảnh động", slug: "anh-dong", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Animal", slug: "animal", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Animal Girl",
    slug: "animal-girl",
    category: "general",
    description:
      'Nhân vật nữ mang đặc điểm động vật như tai, đuôi, móng vuốt (mèo, chó, cáo, thỏ...). Tính cách thường dễ thương hoặc hoang dã, gợi cảm theo kiểu "nửa người nửa thú".',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Áo dài", slug: "ao-dai", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Apron",
    slug: "apron",
    category: "general",
    description:
      'Tạp dề không nội y. Nhân vật nữ chỉ mặc duy nhất chiếc tạp dề mỏng, thường là vợ đảm, mẹ kế hoặc cô gái phục vụ trong nhà – mang cảm giác "nguy hiểm trong an toàn".',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Artist CG",
    slug: "artist-cg",
    category: "general",
    description:
      "Bộ tranh vẽ minh họa (CG – computer graphic) từ các họa sĩ hentai nổi tiếng. Thường không có cốt truyện rõ, chủ yếu là các cảnh sex chất lượng cao và tạo hình đẹp.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Based Game",
    slug: "based-game",
    category: "general",
    description:
      'Nội dung hentai được chuyển thể từ game người lớn. Có thể giữ nguyên tạo hình, tình huống và bối cảnh của game gốc.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "BDSM",
    slug: "bdsm",
    category: "general",
    description:
      "Trói buộc, kiểm soát, đau đớn, phục tùng. Gồm nhiều cấp độ: từ nhẹ (bịt mắt, trói tay) đến nặng (đánh, tra tấn, điều khiển tâm lý).",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Big Ass",
    slug: "big-ass",
    category: "general",
    description: "Tập trung vào nhân vật nữ có vòng 3 to, tròn, căng mẩy.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Big Boobs",
    slug: "big-boobs",
    category: "general",
    description:
      "Vòng 1 ngoại cỡ, thường rung động mạnh khi va chạm. Nét vẽ được phóng đại chuyển động và độ căng mọng của ngực.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Big Penis",
    slug: "big-penis",
    category: "general",
    description:
      "Dương vật ngoại cỡ, quá khổ so với bình thường. Nhấn mạnh sự đau đớn – sung sướng cực độ từ việc bị “nhồi nhét” quá mức.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Bikini", slug: "bikini", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Bịt mắt",
    slug: "bit-mat",
    category: "general",
    description:
      "Quan hệ tình dục khi một hoặc cả hai nhân vật bị bịt mắt, tạo cảm giác bí ẩn và tăng cường kích thích qua sự bất ngờ.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Black Skin", slug: "black-skin", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Blackmail",
    slug: "blackmail",
    category: "general",
    description:
      "Cưỡng ép quan hệ bằng cách uy hiếp, đe dọa (bằng ảnh, clip, bí mật...). Tình huống thường căng thẳng, nhân vật rơi vào trạng thái vừa chống cự vừa bị kích thích.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "BlowJobs",
    slug: "blowjobs",
    category: "general",
    description:
      "Dùng miệng để kích thích dương vật. Có thể đi kèm các kỹ thuật sâu như lick, suck, deepthroat.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Body Swap", slug: "body-swap", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Bodysuit",
    slug: "bodysuit",
    category: "general",
    description:
      "Trang phục bó sát toàn thân (như latex, da bóng). Tôn lên đường cong, tạo cảm giác ngộp thở, quyến rũ và ướt át.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Bondage", slug: "bondage", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "BreastJobs",
    slug: "breastjobs",
    category: "general",
    description:
      "Kẹp dương vật giữa hai bầu ngực và di chuyển lên xuống để kích thích. Thường đi kèm với cảnh xuất tinh lên mặt hoặc ngực.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Brocon", slug: "brocon", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Brother", slug: "brother", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Business Suit",
    slug: "business-suit",
    category: "general",
    description:
      "Trang phục công sở bó sát – váy bút chì, áo sơ mi ôm, vest nữ. Hình ảnh “chị sếp/ thư ký” gợi cảm.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Che ít", slug: "che-it", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Che nhiều",
    slug: "che-nhieu",
    category: "general",
    description:
      "Nội dung gợi cảm nhưng vẫn kín đáo, tập trung vào trang phục che phủ nhiều nhưng vẫn khêu gợi.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Cheating", slug: "cheating", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Chikan",
    slug: "chikan",
    category: "general",
    description:
      "Quấy rối tình dục nơi công cộng (tàu điện/xe buýt). Nhấn mạnh sự lén lút và cảm giác cấm kỵ.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Chinese Dress",
    slug: "chinese-dress",
    category: "general",
    description:
      "Trang phục sườn xám xẻ cao, ôm sát, khoe đường cong. Thường gợi cảm tinh tế.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Có che", slug: "co-che", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Côn trùng", slug: "con-trung", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Comedy",
    slug: "comedy",
    category: "general",
    description:
      "Tình huống tình dục pha hài hước, các “tai nạn”/hiểu lầm dẫn đến cảnh nóng vui nhộn.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Comic", slug: "comic", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Condom",
    slug: "condom",
    category: "general",
    description:
      "Quan hệ sử dụng bao cao su — nhấn mạnh an toàn hoặc như một chi tiết gợi cảm.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Cousin", slug: "cousin", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Crotch Tattoo",
    slug: "crotch-tattoo",
    category: "general",
    description: "Hình xăm vùng kín, cảm giác nổi loạn, táo bạo.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Cunnilingus",
    slug: "cunnilingus",
    category: "general",
    description:
      "Quan hệ bằng miệng tập trung kích thích âm đạo bằng môi và lưỡi.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Daughter", slug: "daughter", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Dark Skin",
    slug: "dark-skin",
    category: "general",
    description:
      "Làn da nâu/sẫm. Thường được vẽ với vẻ đẹp gợi cảm, mạnh mẽ.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Deepthroat",
    slug: "deepthroat",
    category: "general",
    description:
      "Kỹ thuật ngậm sâu toàn bộ dương vật, thường gây nghẹn – cảm giác mãnh liệt.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Demon", slug: "demon", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "DemonGirl",
    slug: "demongirl",
    category: "general",
    description:
      "Nữ quỷ (sừng/đuôi/ánh mắt dâm đãng), thường chủ động và thống trị.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Devil", slug: "devil", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "DevilGirl", slug: "devilgirl", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Dirty", slug: "dirty", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "DirtyOldMan", slug: "dirtyoldman", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Double Penetration",
    slug: "double-penetration",
    category: "general",
    description:
      "Quan hệ đồng thời qua hai đường (âm đạo & hậu môn).",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Doujinshi",
    slug: "doujinshi",
    category: "general",
    description:
      "Truyện 18+ do fan sáng tác, dùng nhân vật anime/game nổi tiếng hoặc tự tạo.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Drama", slug: "drama", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Drug", slug: "drug", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Ecchi",
    slug: "ecchi",
    category: "general",
    description:
      "Tình huống hớ hênh, đụng chạm vô tình… tạo tình huống nhạy cảm.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Elf",
    slug: "elf",
    category: "general",
    description:
      "Chủng tộc yêu tinh, tai nhọn, mảnh mai; thường trong bối cảnh fantasy.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Fantasy",
    slug: "fantasy",
    category: "general",
    description:
      "Bối cảnh giả tưởng, sinh vật huyền ảo; kết hợp yếu tố tình dục.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Father", slug: "father", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Femdom",
    slug: "femdom",
    category: "general",
    description: "Nữ làm chủ/điều khiển, áp đảo nam trong quan hệ tình dục.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Footjob",
    slug: "footjob",
    category: "general",
    description: "Kích thích dương vật bằng bàn chân.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Full Color",
    slug: "full-color",
    category: "general",
    description:
      "Toàn bộ truyện được tô màu; màu sắc sống động tăng kích thích thị giác.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Furry", slug: "furry", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Futanari", slug: "futanari", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Gangbang", slug: "gangbang", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Ghost", slug: "ghost", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Glasses", slug: "glasses", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Gothic Lolita", slug: "gothic-lolita", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Guro", slug: "guro", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Handjob", slug: "handjob", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Harem",
    slug: "harem",
    category: "general",
    description:
      "Một nhân vật (thường nam) được nhiều nhân vật khác giới vây quanh.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Horror", slug: "horror", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Housewife", slug: "housewife", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Idol", slug: "idol", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Incest", slug: "incest", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Isekai",
    slug: "isekai",
    category: "general",
    description:
      "Nhân vật sang thế giới khác; pha trộn phiêu lưu/ma thuật và tình dục.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Không che", slug: "khong-che", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Kimono", slug: "kimono", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Loli", slug: "loli", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Maids", slug: "maids", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Manhua", slug: "manhua", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Manhwa",
    slug: "manhwa",
    category: "general",
    description:
      "Truyện tranh Hàn Quốc; nét vẽ mượt, hiện đại hoặc giả tưởng; hấp dẫn.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Milf",
    slug: "milf",
    category: "general",
    description:
      "Phụ nữ trưởng thành, quyến rũ, giàu kinh nghiệm (mẹ kế, cô giáo…).",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Mind Break",
    slug: "mind-break",
    category: "general",
    description:
      "Bị ép đến mức tâm trí vỡ vụn/tẩy não do khoái cảm hay áp lực tâm lý.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Mind Control",
    slug: "mind-control",
    category: "general",
    description:
      "Bị thao túng tâm trí bằng ma thuật/thuốc/công nghệ, dẫn đến hành vi ngoài ý muốn.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Monster", slug: "monster", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Mother", slug: "mother", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Nakadashi", slug: "nakadashi", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Netori", slug: "netori", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "NTR",
    slug: "ntr",
    category: "general",
    description:
      "Nhân vật chính bị cắm sừng – người yêu/vợ bị người khác chiếm đoạt.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Nun", slug: "nun", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Nurse", slug: "nurse", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Pregnant", slug: "pregnant", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Princess", slug: "princess", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Quần tất",
    slug: "quan-tat",
    category: "general",
    description:
      "Nhân vật mặc quần tất mỏng, tôn đôi chân, thường rách/kéo xuống tăng gợi cảm.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Rape", slug: "rape", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Romance",
    slug: "romance",
    category: "general",
    description:
      "Tình dục gắn liền với tình yêu, đồng thuận, nhiều cảm xúc, không bạo lực.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "School uniform", slug: "school-uniform", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "SchoolGirl",
    slug: "schoolgirl",
    category: "general",
    description:
      "Nữ sinh 16–18 tuổi, đồng phục váy ngắn, bối cảnh trường/ký túc xá/thư viện.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Sex Toys", slug: "sex-toys", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Shota", slug: "shota", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Siscon", slug: "siscon", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Sister", slug: "sister", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Slave", slug: "slave", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Sleeping", slug: "sleeping", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Small Boobs", slug: "small-boobs", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Soft Incest",
    slug: "soft-incest",
    category: "general",
    description:
      "Quan hệ/tình cảm họ hàng xa (anh họ–em họ, con riêng–mẹ kế…), không huyết thống trực tiếp.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Son", slug: "son", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Sport", slug: "sport", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Squirting",
    slug: "squirting",
    category: "general",
    description:
      "Nữ đạt cực khoái phun nước mạnh mẽ, nhấn mạnh sự mãnh liệt và chân thực.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Stockings", slug: "stockings", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Swimsuit",
    slug: "swimsuit",
    category: "general",
    description:
      "Đồ bơi (bikini/one-piece) ở bãi biển/hồ bơi; gợi cảm trẻ trung.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Teacher", slug: "teacher", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Tentacles", slug: "tentacles", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Time Stop", slug: "time-stop", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Tomboy", slug: "tomboy", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Truyện Việt", slug: "truyen-viet", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Tsundere",
    slug: "tsundere",
    category: "general",
    description:
      "Ngoài lạnh trong ấm; tương phản tính cách khi vào cảnh thân mật.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Twins", slug: "twins", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Underwater", slug: "underwater", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Vanilla",
    slug: "vanilla",
    category: "general",
    description:
      "Cảnh sex nhẹ nhàng, đồng thuận; tập trung kết nối cảm xúc.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { name: "Virgin", slug: "virgin", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Webtoon", slug: "webtoon", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "X-ray", slug: "x-ray", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  { name: "Yandere", slug: "yandere", category: "general", description: "", createdAt: new Date(), updatedAt: new Date() },
  {
    name: "Yaoi",
    slug: "yaoi",
    category: "general",
    description:
      "Quan hệ giữa hai nam; có thể lãng mạn/đam mỹ, phổ biến trong cộng đồng BL.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Yuri",
    slug: "yuri",
    category: "general",
    description:
      "Quan hệ giữa hai nữ; nhấn mạnh sự lãng mạn/gợi cảm, nhẹ nhàng hoặc mãnh liệt.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]);
