db.genres.insertMany([
  {
    name: "Big Boobs",
    slug: "big-boobs",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Vanilla",
    slug: "vanilla",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Full Color",
    slug: "full-color",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ecchi",
    slug: "ecchi",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "SchoolGirl",
    slug: "schoolgirl",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Harem",
    slug: "harem",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Incest",
    slug: "incest",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "NTR (Netorare)",
    slug: "ntr-netorare",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Doujinshi",
    slug: "doujinshi",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "BlowJobs",
    slug: "blowjobs",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Anal",
    slug: "anal",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Big Ass",
    slug: "big-ass",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ahegao",
    slug: "ahegao",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Milf",
    slug: "milf",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Romance",
    slug: "romance",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Cosplay",
    slug: "cosplay",
    category: "most_viewed",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "3D Hentai",
    slug: "3d-hentai",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Angel",
    slug: "angel",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Áo Dài",
    slug: "ao-dai",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "BDSM",
    slug: "bdsm",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Bodysuit",
    slug: "bodysuit",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Business Suit",
    slug: "business-suit",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Cheating",
    slug: "cheating",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Cousin",
    slug: "cousin",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Deepthroat",
    slug: "deepthroat",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "DevilGirl",
    slug: "devilgirl",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Drama",
    slug: "drama",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Femdom",
    slug: "femdom",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Action",
    slug: "action",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ảnh động",
    slug: "anh-dong",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Apron",
    slug: "apron",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Big Penis",
    slug: "big-penis",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "BreastJobs",
    slug: "breastjobs",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Catgirls",
    slug: "catgirls",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Chinese Dress",
    slug: "chinese-dress",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Crotch Tattoo",
    slug: "crotch-tattoo",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Demon",
    slug: "demon",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Dirty",
    slug: "dirty",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Elf",
    slug: "elf",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Footjob",
    slug: "footjob",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Adult",
    slug: "adult",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Animal",
    slug: "animal",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Artist CG",
    slug: "artist-cg",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Blackmail",
    slug: "blackmail",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Brocon",
    slug: "brocon",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Che ít",
    slug: "che-it",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Comedy",
    slug: "comedy",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Dark Skin",
    slug: "dark-skin",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "DemonGirl",
    slug: "demongirl",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "DirtyOldMan",
    slug: "dirtyoldman",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Fantasy",
    slug: "fantasy",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Furry",
    slug: "furry",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Adventure",
    slug: "adventure",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Animal girl",
    slug: "animal-girl",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Based Game",
    slug: "based-game",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Body Swap",
    slug: "body-swap",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Brother",
    slug: "brother",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Che nhiều",
    slug: "che-nhieu",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Comic",
    slug: "comic",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Daughter",
    slug: "daughter",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Devil",
    slug: "devil",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Double Pentration",
    slug: "double-pentration",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Father",
    slug: "father",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Futanari",
    slug: "futanari",
    category: "other",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Loli",
    slug: "loli",
    category: "hardcore",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Animal",
    slug: "animal",
    category: "hardcore",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Shota",
    slug: "shota",
    category: "hardcore",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Côn trùng",
    slug: "con-trung",
    category: "hardcore",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Futanari",
    slug: "futanari",
    category: "hardcore",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Guro",
    slug: "guro",
    category: "hardcore",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Furry",
    slug: "furry",
    category: "hardcore",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]);
