const defaultPityData = [
  {
    level: 1,
    label: "Cấp 1",
    star1: 100,
    star2: 0,
    star3: 0,
    star4: 0,
    star5: 0,
    total: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    level: 2,
    label: "Cấp 2",
    star1: 90,
    star2: 8,
    star3: 2,
    star4: 0,
    star5: 0,
    total: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    level: 3,
    label: "Cấp 3",
    star1: 70,
    star2: 25,
    star3: 5,
    star4: 0,
    star5: 0,
    total: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    level: 4,
    label: "Cấp 4",
    star1: 53.291,
    star2: 30,
    star3: 15,
    star4: 1.7,
    star5: 0.009,
    total: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    level: 5,
    label: "Cấp 5",
    star1: 44.99,
    star2: 33,
    star3: 20,
    star4: 2,
    star5: 0.01,
    total: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    level: 6,
    label: "Cấp 6",
    star1: 24.95,
    star2: 40,
    star3: 30,
    star4: 5,
    star5: 0.05,
    total: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    level: 7,
    label: "Cấp 7",
    star1: 19,
    star2: 30,
    star3: 35,
    star4: 15,
    star5: 1,
    total: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    level: 8,
    label: "Cấp 8",
    star1: 15,
    star2: 20,
    star3: 35,
    star4: 25,
    star5: 5,
    total: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    level: 9,
    label: "Cấp 9",
    star1: 10,
    star2: 15,
    star3: 30,
    star4: 30,
    star5: 15,
    total: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

db.pities.insertMany(defaultPityData);
